# Change these first
owner: ducpw # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: epp server
    url: http://139.99.46.78
  - name: Preseed
    url: https://ubuntu.pages.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cu.al
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status Page"
  introMessage: Status Page
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
